### ISSUE TITLE
information issue in CrowdAlert-Mobile/ios/CrowdAlert/Info.plist

### ISSUE THREAD

**Issue by seepls** [AOSSIE-Org/CrowdAlert-Mobile#3]
the iOS  bundle Identifier not assigned a value . without which can not set up for iOS 
<img width="1440" alt="screenshot 2018-12-31 at 6 20 03 pm" src="https://user-images.githubusercontent.com/40840674/50560702-6fadeb80-0d29-11e9-9427-16f9af393c5e.png">

**Comment by heychirag** [comment]
@seepls This is just a mirror repository. Please open an issue [here](https://gitlab.com/aossie/CrowdAlert-Mobile).
